src/Entity/VinylMix.php
<?php

namespace App\Entity;

use App\Repository\VinylMixRepository;
use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VinylMixRepository::class)]
class VinylMix
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(nullable: true)]
    private ?int $trackCount = null;

    #[ORM\Column(length: 255)]
    private ?string $genre = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(nullable: true)]
    private ?int $vote = 0;

    public function __construct(){
        $this->createdAt = new DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }


    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTrackCount(): ?int
    {
        return $this->trackCount;
    }

    public function setTrackCount(?int $trackCount): self
    {
        $this->trackCount = $trackCount;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getVote(): ?int
    {
        return $this->vote;
    }

    public function setVote(?int $vote): self
    {
        $this->vote = $vote;

        return $this;
    }

    public function getVotesString(): string {
        $prefix = $this->getVote() > 0 ? '+' : ($this->getVote() < 0 ? '-' : '');
        return sprintf("%s%d", $prefix, abs($this->getVote()));
    }

    public function getImageUrl(int $width): string {
        return sprintf('https://picsum.photos/id/%d/%d', ($this->getId() + 50) % 1000, $width);
    }
}

src/Controller/ControllerPage.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ControllerPage{
    #[Route('/browse/{genre}/{numpage}', name: 'blog_list', requirements: ['numpage' => '\d+'])]
    public function controllerPage(string $genre, string $numpage): Response
    {
        return new Response($genre.'/'.$numpage);
    }
}

src/Controller/MixController.php
<?php

namespace App\Controller;

use App\Entity\VinylMix;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use function Symfony\Component\String\u;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MixController extends AbstractController
{
    #[Route('/mix/new', name: 'new')]
    public function mixController(EntityManagerInterface $eM): Response
    {
        $mix = new VinylMix;
        $genre = array('Pop', 'Rock', 'Heavy_Metal', 'Zouk', 'Soul', 'Jazz');
        $mix->setTitle('Titre de mon mix')
            ->setDescription('La description de mon mix')
            ->setTitle('This is my title')
            ->setGenre($genre[array_rand($genre)])
            ->setVote(rand(-10, 10))
            ->setTrackCount(rand(1, 100));

        $eM->persist($mix);

        //Method to persist all data manages
        $eM->flush();

        dd($mix);
        return new Response();
    }

    #[Route('/browse/{slug}', name: 'app_randomGenre')]
    public function randomGenre(EntityManagerInterface $em, string $slug = null): Response
    {
        /** @var VinylMixRepository */
        $repository = $em->getRepository(VinylMix::class);
        //dd($slug);
        $a = $repository->filterByGenre($slug);
        $genre = $slug ? u(str_replace('-', ' ', $slug))->title(true) : null;

        return $this->render(
            'vinyl/browse.html.twig',
            [
                'genre' => $genre,
                'mix' => $a,
            ]
        );
    }




    #[Route('mix/{id}', name: 'mix')]
    public function show(VinylMix $mix): Response
    {
        return $this->render('mix/show.html.twig', ['mix' => $mix]);
    }

    #[Route('/mix/{id}/vote', name: 'mix_vote', methods: ['POST'])]
    public function vote(VinylMix $mix, Request $request, EntityManagerInterface $em): Response
    {
        if($request->request->get('direction') == 'up'){
            $mix->setVote($mix->getVote() + 1);
        }else{
            $mix->setVote($mix->getVote() - 1);
        }
        
        $em->flush();
        $this->addFlash('success', "Votre vote a bien été enregistré");
        return $this->redirectToRoute('mix', ['id' => $mix->getId()]);
    }
}

src/Controller/SongApiController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Psr\Log\LoggerInterface;

class SongApiController extends AbstractController
{
    #[Route('/api/song/{id<\d+>}', name: 'app_song_api', methods: 'GET')]
    public function index(LoggerInterface $logI, string $id): Response
    {
        $song = [
            'id' => $id,
            'name' => 'Waterfalls',
            'url' => 'https://symfonycasts.s3.amazonaws.com/sample.mp3',
        ];
        $logI->info('Returning API response for song'.$id);
        return new JsonResponse($song);
    }
}

src/Controller/VinylController.php
<?php

namespace App\Controller;

use Twig\Environment;
use App\Entity\VinylMix;
use App\Repository\VinylMixRepository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManagerInterface;
use function Symfony\Component\String\u;
use Symfony\Contracts\Cache\CacheInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\HttpClient\HttpClientInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class VinylController extends AbstractController
{
    #[Route('/', name: 'app_homepage')]
    public function homepage(Environment $env): Response
    {
        $html = $env->render('/vinyl/homepage.html.twig', [
            'title'  => 'Crazy frog',
            'tab' => $this->getSongsTitles(),
        ]);


        return new Response($html);
    }
    private function getSongsTitles(): array
    {
        $tableau = [
            ['song' => 'Gangsta\'s Paradise', 'artist' => 'Coolio'],
            ['song' => 'Waterfalls', 'artist' => 'TLC'],
            ['song' => 'Creep', 'artist' => 'Radiohead'],
            ['song' => 'Kiss from a Rose', 'artist' => 'Seal'],
            ['song' => 'On Bended Knee', 'artist' => 'Boyz II Men'],
            ['song' => 'Fantasy', 'artist' => 'Mariah Carey'],
        ];
        return $tableau;
    }
    
}

templates/api/song_api/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SongApiController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/home/oissuya/Documents/Projets/oissuyaProjet/src/Controller/Api/SongApiController.php'|file_link(0) }}">src/Controller/Api/SongApiController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/home/oissuya/Documents/Projets/oissuyaProjet/templates/api/song_api/index.html.twig'|file_link(0) }}">templates/api/song_api/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Mixed Vinyl{% endblock %}</title>

        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300;400;700&display=swap" rel="stylesheet">

        {% set url = asset('styles/app.css')  %}
        <link href={{ url }}  rel="stylesheet" />

        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>

        <!-- Main Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark  mb-5" style="background-color: #27333A;">
            <div class="container-fluid">
                <a class="navbar-brand" href={{ path('app_homepage') }}>
                    <i class="fas fa-record-vinyl"></i>
                    Mixed Vinyl
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" style="margin-top: 20px;" href={{ path('app_randomGenre') }}>Browse Mixes</a>
                        </li>
                        <!-- Not Authenticated -->
                            <!-- <li class="nav-item"><button href="#" class="btn btn-primary btn-sm">Login</button></li> -->
                        <!-- End Not Authenticated -->

                        <!-- If Authenticated -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fas fa-user-astronaut p-2" style="border: solid 1px #fff; border-radius: 50px; font-size: 40px;"></i>
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="dropdown-item" href="#">My Mixes</a></li>
                                <li><a class="dropdown-item" href="#">Signout</a></li>
                            </ul>
                        </li>
                        <!-- End If Authenticated -->
                    </ul>
                </div>
            </div>
        </nav>
        <!-- End Main Navigation -->

        {% block body %}{% endblock %}

        <!-- Footer -->
        <div class="container mt-5">
            <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
                <div class="col-md-4 d-flex align-items-center">
                    <span class="me-1" style="color: red;"><i class="fas fa-heart"></i></span>
                    <span class="text-muted me-1">The guys and gals at</span>
                    <a target="_blank" href="https://symfonycasts.com/" style="color: #25a1dd" class="mb-3 me-2 mb-md-0 text-decoration-none lh-1">
                        SymfonyCasts
                    </a>
                </div>

                <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                    <li class="ms-3"><a class="text-muted" target="_blank" href="https://github.com/SymfonyCasts/symfony6"><i class="fab fa-github"></i></a></li>
                </ul>
            </footer>
        </div>
        <!-- End Footer -->

    </body>
</html>

templates/mix/_recordSvg.html.twig
<svg width="100%" height="100%" viewBox="0 0 496 496" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs>
        <linearGradient x1="50%" y1="0%" x2="50%" y2="100%" id="linearGradient-1">
            <stop stop-color="#C380F3" offset="0%"></stop>
            <stop stop-color="#4A90E2" offset="100%"></stop>
        </linearGradient>
    </defs>
    <g id="Mixed-Vinyl" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="Group">
            <g id="record-vinyl" fill="#000000" fill-rule="nonzero">
                <path d="M248,144 C190.562386,144 144,190.562386 144,248 C144,305.437614 190.562386,352 248,352 C305.437614,352 352,305.437614 352,248 C352,190.562386 305.437614,144 248,144 L248,144 Z M248,272 C234.745166,272 224,261.254834 224,248 C224,234.745166 234.745166,224 248,224 C261.254834,224 272,234.745166 272,248 C272,261.254834 261.254834,272 248,272 Z M248,0 C111,0 0,111 0,248 C0,385 111,496 248,496 C385,496 496,385 496,248 C496,111 385,0 248,0 Z M248,376 C177.307552,376 120,318.692448 120,248 C120,177.307552 177.307552,120 248,120 C318.692448,120 376,177.307552 376,248 C376,281.947711 362.514324,314.505012 338.509668,338.509668 C314.505012,362.514324 281.947711,376 248,376 Z" id="Shape"></path>
            </g>
            <g id="record-vinyl" transform="translate(144.000000, 144.000000)" fill="url(#linearGradient-1)" fill-rule="nonzero">
                <path d="M104,0 C46.562386,0 0,46.562386 0,104 C0,161.437614 46.562386,208 104,208 C161.437614,208 208,161.437614 208,104 C208,46.562386 161.437614,0 104,0 L104,0 Z M104,128 C90.745166,128 80,117.254834 80,104 C80,90.745166 90.745166,80 104,80 C117.254834,80 128,90.745166 128,104 C128,117.254834 117.254834,128 104,128 Z" id="Shape"></path>
            </g>
            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="235"></circle>
            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="215"></circle>
            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="195"></circle>
            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="175"></circle>
            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="155"></circle>
        </g>
    </g>
</svg>

templates/mix/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MixController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/home/oissuya/Documents/Projets/oissuyaProjet/src/Controller/MixController.php'|file_link(0) }}">src/Controller/MixController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/home/oissuya/Documents/Projets/oissuyaProjet/templates/mix/index.html.twig'|file_link(0) }}">templates/mix/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/mix/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ mix.title }} Mix{% endblock %}

{% block body %}

{% for message in app.flashes('success') %}
<div class="alert alert-success">
    <center> <b><font size="+2">{{ message }}</font></b> </center>
</div>
{% endfor %}

    <div class="container">
        <h1 class="d-inline me-3">{{ mix.title }}</h1>
        <div class="row mt-5">
            <div class="col-12 col-md-4">

                {% include "mix/_recordSvg.html.twig" %}

            </div>


            <div class="col-12 col-md-8 ps-5">
                <h2 class="mb-4">{{ mix.trackCount }} songs <small>(genre: {{ mix.genre }})</small></h2> 
                    <p>{{ mix.description }}</p> 
                    {{ mix.votesString }} votes 
                    <form action={{ path('mix_vote', { id: mix.id }) }} method="POST">
                        <button
                            name="direction"
                            value="up"
                            type="submit"
                            class="btn btn-outline-primary"
                        ><span class="fa fa-thumbs-up"></span>
                        </button>

                        <button
                            name="direction"
                            value="down"
                            type="submit"
                            class="btn btn-outline-primary"
                        ><span class="fa fa-thumbs-down"></span>
                        </button>
                    </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/song_api/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SongApiController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/home/oissuya/Documents/Projets/oissuyaProjet/src/Controller/SongApiController.php'|file_link(0) }}">src/Controller/SongApiController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/home/oissuya/Documents/Projets/oissuyaProjet/templates/song_api/index.html.twig'|file_link(0) }}">templates/song_api/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/vinyl/browse.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">
    <h1>Browse Vinyl Mixes</h1>

    <h2 class="mt-5 mb-4">Filter by Genre</h2>
    <ul class="genre-list ps-0 mt-2 mb-3">
        <li class="d-inline">
           
            <a class="btn btn-primary btn-sm" href={{ path('app_randomGenre', { slug: 'Pop' }) }}>pop</a>
        </li>
        <li class="d-inline">
            <a class="btn btn-primary btn-sm" href={{ path('app_randomGenre', { slug: 'Rock' }) }}>rock</a>
        </li>
        <li class="d-inline">
            <a class="btn btn-primary btn-sm" href={{ path('app_randomGenre', { slug: 'Heavy_Metal' }) }}>heavy Metal</a>
        </li>
        <li class="d-inline">
            <a class="btn btn-primary btn-sm" href={{ path('app_randomGenre', { slug: 'Zouk' }) }}>Zouk</a>
        </li>
    </ul>


    <div>
        <h2 class="mt-5">Mixes</h2>
        <div class="row">
            {% for element in mix %}
                <div class="col col-md-4">
                    <div class="mixed-vinyl-container p-3 text-center">
                            <a href={{ path('mix', { id: element.id}) }}>
                                <img src={{ element.getImageUrl(200) }} data-src="https://via.placeholder.com/200" alt="Square placeholder img">
                            </a>
                            <p class="mt-2"><strong>{{ element.title }}</strong></p>
                            <span>{{ element.trackCount }}</span> | <span>{{ element.genre }}</span> | <span> {{ element.createdAt|ago }} {{ element.getVotesString() }} </span>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/vinyl/homepage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create a new Record | {{ parent() }}{% endblock %}

{% block body %}
<div class="container">
    <h1 class="d-inline me-3">PB & Jams</h1> <i class="fas fa-edit"></i>
    <div class="row mt-5">
        <div class="col-12 col-md-4">

            {% include "mix/_recordSvg.html.twig" %}

        </div>
        <div class="col-12 col-md-8 ps-5">
            <h2 class="mb-4">10 songs (30 minutes of 60 still available)</h2>
            {% for key, t in tab %}
                <div class="song-list">
                    <div class="d-flex mb-3">
                        <a href="#">
                            <i class="fas fa-play me-3"></i>
                        </a>
                        <span class="song-details"> {{ t.artist ~ ' - ' ~ t.song}}</span>
                        <a href="#">
                            <i class="fas fa-bars mx-3"></i>
                        </a>
                        <a href="#">
                            <i class="fas fa-times"></i>
                        </a>
                    </div>
                </div>
            {% endfor %}
            <button type="button" class="btn btn-success"><i class="fas fa-plus"></i> Add a song</button>
        </div>
    </div>
</div>
{% endblock %}